[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.5.0"
  export = ["choreo_perf_test_sample"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "choreo_perf_test_sample"
  org = "choreopmm"
  version = "3.1.1"

